### PR TITLE
Next

### LINKED ISSUE #105: Mantine inputs not working
## Description

Using mantine inputs such as Select, TextInput under cell() will not work

## Expected Behaviour

Inputs such as Select should show the dropdown list

## Additional Information

https://codesandbox.io/s/mantine-data-grid-starter-forked-gr6krh?file=/src/DataGrid.tsx
Removing this line ```{...form.getInputProps(`test`)}``` will make the input work but the data will not be binded to form

### PR DESCRIPTION
**Pull request by Kuechlin**
Closes #105, #117, #120, #122

## Description

fix some issues

### CODE REVIEW

File: src/ColumnFilter.tsx [hunk 1]
```diff
@@ -67,8 +67,15 @@ export const ColumnFilter = ({ column, className, color }: ColumnFilterProps) =>
             <Element filter={state.value} onFilterChange={change} />
 
             <Group position="apart">
-              <Button children={<X />} color="gray" onClick={clear} compact type="reset" />
-              <Button children={<Check />} onClick={save} compact variant="outline" type="submit" />
+              <Button children={<X />} color="gray" onClick={clear} compact type="reset" aria-label="Reste Filter" />
```
Comment (ShahriarKh) [inline src/ColumnFilter.tsx:70]: Typo: Reste Filter => Reset Filter
